title: Waste is a thief
repository: steve-hawkins/waste-is-a-thief
author: Steven Hawkins
email: "steven.hawkins84@gmail.com"
description: >-
  My thoughts and findings on sustainable software product innovations.
baseurl: ""
url: "https://steve-hawkins.github.io"
plugins:
  - jekyll-remote-theme
  - jekyll-youtube
remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/steve-hawkins"}
