title: waste is a thief
repository: steve-hawkins/waste-is-a-thief
author: Steve Hawkins
email: "steven.hawkins84@gmail.com"
description: >-
  A personal blog with my thoughts and findings on sustainable software product innovations.
baseurl: ""
url: "https://blog.wiat.io"
defaults:
  -
    scope:
      path: ""
    values:
      author: "Steve Hawkins"
plugins:
  - jekyll-remote-theme
  - jekyll-youtube
remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/steve-hawkins"}
    - { platform: linkedin, user_url: "https://linkedin.com/in/steve--hawkins"}
